<?php

namespace App\Support;

use Illuminate\Support\Str;

class GeoparkData
{
    public static function items(): array
    {
        return [
            'geologi' => [
                [
                    'nama' => 'Lava Erupsi 1907 Tubo',
                    'slug' => 'lava-erupsi-1907-tubo',
                    'image' => 'tubo.jpg',
                    'lokasi' => 'Kelurahan Tubo, Ternate Utara, Kota Ternate',
                    'x' => '127.375278',
                    'y' => '0.829722',
                    'kelurahan' => 'Tubo',
                    'kecamatan' => 'Ternate Utara',
                    'kota' => 'Kota Ternate',
                    'deskripsi' => 'Sisa aliran lava dari letusan 1907 yang masih menampilkan struktur basaltik keras dan lapisan lava beku.',
                ],
                [
                    'nama' => 'Lava Erupsi 1737 Batu Angus',
                    'slug' => 'lava-erupsi-1737-batu-angus',
                    'image' => 'batuangus.png',
                    'lokasi' => 'Kelurahan Kulaba, Ternate Barat, Kota Ternate',
                    'x' => '127.365511',
                    'y' => '0.846504',
                    'kelurahan' => 'Kulaba',
                    'kecamatan' => 'Ternate Barat',
                    'kota' => 'Kota Ternate',
                    'deskripsi' => 'Singkapan lava dan tufa hasil letusan besar 1737, nama Batu Angus muncul karena warna hitam pekat yang terbakar.',
                ],
                [
                    'nama' => 'Teras Pantai Tobololo',
                    'slug' => 'teras-pantai-tobololo',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kelurahan Tobololo, Ternate Barat, Kota Ternate',
                    'x' => '127.350372',
                    'y' => '0.855883',
                    'kelurahan' => 'Tobololo',
                    'kecamatan' => 'Ternate Barat',
                    'kota' => 'Kota Ternate',
                    'deskripsi' => 'Formasi teras pantai yang terbentuk dari kombinasi endapan volkanik dan gerusan laut, mencerminkan dinamika geologi pesisir.',
                ],
                [
                    'nama' => 'Lava Erupsi 1763 Pantai Masirete',
                    'slug' => 'lava-erupsi-1763-pantai-masirete',
                    'image' => 'sulamadaha.jpg',
                    'lokasi' => 'Kelurahan Sulamadaha, Ternate Barat, Kota Ternate',
                    'x' => '127.341100',
                    'y' => '0.862821',
                    'kelurahan' => 'Sulamadaha',
                    'kecamatan' => 'Ternate Barat',
                    'kota' => 'Kota Ternate',
                    'deskripsi' => 'Aliran lava tua dari letusan 1763 yang mengubah morfologi pantai Masirete menjadi hamparan batuan vulkanik.',
                ],
                [
                    'nama' => 'Lava Pahoehoe Sulamadaha',
                    'slug' => 'lava-pahoehoe-sulamadaha',
                    'image' => 'sulamadaha.jpg',
                    'lokasi' => 'Kelurahan Sulamadaha, Ternate Barat, Kota Ternate',
                    'x' => '127.337235',
                    'y' => '0.863167',
                    'kelurahan' => 'Sulamadaha',
                    'kecamatan' => 'Ternate Barat',
                    'kota' => 'Kota Ternate',
                    'deskripsi' => 'Permukaan lava halus pahoehoe yang khas, menunjukkan aliran magma yang relatif lama dan efusif.',
                ],
                [
                    'nama' => 'Lava Erupsi 1763 Pantai Jikomalomo',
                    'slug' => 'lava-erupsi-1763-pantai-jikomalomo',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kelurahan Takome, Ternate Barat, Kota Ternate',
                    'x' => '127.321149',
                    'y' => '0.863436',
                    'kelurahan' => 'Takome',
                    'kecamatan' => 'Ternate Barat',
                    'kota' => 'Kota Ternate',
                    'deskripsi' => 'Endapan lava dan material vulkanik dari erupsi 1763 yang masih terlihat di garis pantai barat.',
                ],
                [
                    'nama' => 'Maar Tolire',
                    'slug' => 'maar-tolire',
                    'image' => 'tolire1.jpg',
                    'lokasi' => 'Kelurahan Takome, Ternate Barat, Kota Ternate',
                    'x' => '127.310759',
                    'y' => '0.836734',
                    'kelurahan' => 'Takome',
                    'kecamatan' => 'Ternate Barat',
                    'kota' => 'Kota Ternate',
                    'deskripsi' => 'Kawah maar freatomagmatik yang terisi air, terkenal dengan legenda lokal dan nilai ilmiah sebagai situs letusan air-magma.',
                ],
                [
                    'nama' => 'Endapan Paleotsunami Loto',
                    'slug' => 'endapan-paleotsunami-loto',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kelurahan Loto, Ternate Barat, Kota Ternate',
                    'x' => '127.294870',
                    'y' => '0.821315',
                    'kelurahan' => 'Loto',
                    'kecamatan' => 'Ternate Barat',
                    'kota' => 'Kota Ternate',
                    'deskripsi' => 'Lapisan sedimen pantai yang menunjukkan jejak tsunami purba, penting untuk memahami sejarah bencana geologi.',
                ],
                [
                    'nama' => 'Tebing Breksi Togafo',
                    'slug' => 'tebing-breksi-togafo',
                    'image' => 'benteng.jpg',
                    'lokasi' => 'Kelurahan Togafo, Ternate Barat, Kota Ternate',
                    'x' => '127.293611',
                    'y' => '0.808611',
                    'kelurahan' => 'Togafo',
                    'kecamatan' => 'Ternate Barat',
                    'kota' => 'Kota Ternate',
                    'deskripsi' => 'Tebing breksi vulkanik dengan fragmen batuan beragam, merekam ledakan kuat dari aktivitas magmatik masa lalu.',
                ],
                [
                    'nama' => 'Endapan Piroklastik Bukit Afe Taduma',
                    'slug' => 'endapan-piroklastik-bukit-afe-taduma',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kelurahan Afe Taduma, Pulau Ternate, Kota Ternate',
                    'x' => '127.294234',
                    'y' => '0.807829',
                    'kelurahan' => 'Afe Taduma',
                    'kecamatan' => 'Pulau Ternate',
                    'kota' => 'Kota Ternate',
                    'deskripsi' => 'Lapisan piroklastik tebal yang tersusun dari abu panas dan bongkah batu, bukti runtuhan awan panas masa lalu.',
                ],
                [
                    'nama' => 'Endapan Lahar Kastela',
                    'slug' => 'endapan-lahar-kastela',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kelurahan Kastela, Pulau Ternate, Kota Ternate',
                    'x' => '127.315000',
                    'y' => '0.765556',
                    'kelurahan' => 'Kastela',
                    'kecamatan' => 'Pulau Ternate',
                    'kota' => 'Kota Ternate',
                    'deskripsi' => 'Areal lahar yang terbentuk saat aliran material vulkanik bercampur air, mengalir sampai pesisir dan mengubah lanskap.',
                ],
                [
                    'nama' => 'Sumbat Lava Foramadiahi',
                    'slug' => 'sumbat-lava-foramadiahi',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kelurahan Foramadiahi, Pulau Ternate, Kota Ternate',
                    'x' => '127.321389',
                    'y' => '0.772222',
                    'kelurahan' => 'Foramadiahi',
                    'kecamatan' => 'Pulau Ternate',
                    'kota' => 'Kota Ternate',
                    'deskripsi' => 'Sumbat lava yang mengisi saluran magma dan kemudian terangkat, memperlihatkan proses intrusi magmatik.',
                ],
                [
                    'nama' => 'Kekar Lembar Sasa',
                    'slug' => 'kekar-lembar-sasa',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kelurahan Sasa, Ternate Selatan, Kota Ternate',
                    'x' => '127.320628',
                    'y' => '0.768725',
                    'kelurahan' => 'Sasa',
                    'kecamatan' => 'Ternate Selatan',
                    'kota' => 'Kota Ternate',
                    'deskripsi' => 'Kekar lembar pada lava yang tergores dan terpisah, menunjukkan pendinginan cepat dan kontraksi batuan.',
                ],
                [
                    'nama' => 'Ketidakselarasan Sasa',
                    'slug' => 'ketidakselarasan-sasa',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kelurahan Sasa, Ternate Selatan, Kota Ternate',
                    'x' => '127.324216',
                    'y' => '0.764856',
                    'kelurahan' => 'Sasa',
                    'kecamatan' => 'Ternate Selatan',
                    'kota' => 'Kota Ternate',
                    'deskripsi' => 'Singkapan ketidakselarasan stratigrafi yang mengindikasikan perubahan lingkungan pengendapan sejak masa lalu.',
                ],
                [
                    'nama' => 'Lapisan Batuapung Fitu',
                    'slug' => 'lapisan-batuapung-fitu',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kelurahan Fitu, Ternate Selatan, Kota Ternate',
                    'x' => '127.3441639',
                    'y' => '0.7675889',
                    'kelurahan' => 'Fitu',
                    'kecamatan' => 'Ternate Selatan',
                    'kota' => 'Kota Ternate',
                    'deskripsi' => 'Lapisan batuapung yang menunjukkan letusan eksplosif, biasanya terbentuk dari abu dan fragmen ringan.',
                ],
                [
                    'nama' => 'Maar Ngade',
                    'slug' => 'maar-ngade',
                    'image' => 'ngade.jpg',
                    'lokasi' => 'Kelurahan Ngade, Ternate Selatan, Kota Ternate',
                    'x' => '127.348997',
                    'y' => '0.75939',
                    'kelurahan' => 'Ngade',
                    'kecamatan' => 'Ternate Selatan',
                    'kota' => 'Kota Ternate',
                    'deskripsi' => 'Kawah maar dangkal dengan karakter freatomagmatik, terbentuk oleh kontak antara air tanah dan magma.',
                ],
                [
                    'nama' => 'Endapan Freatomagmatik Kalumata',
                    'slug' => 'endapan-freatomagmatik-kalumata',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kelurahan Kalumata, Ternate Selatan, Kota Ternate',
                    'x' => '127.353325',
                    'y' => '0.770551',
                    'kelurahan' => 'Kalumata',
                    'kecamatan' => 'Ternate Selatan',
                    'kota' => 'Kota Ternate',
                    'deskripsi' => 'Deposit freatomagmatik kaya akan fragmen kaca vulkanik dan pasir, bukti kontak letusan antara air dan magma.',
                ],
                [
                    'nama' => 'Lava Mujiumajiko',
                    'slug' => 'lava-mujiumajiko',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kelurahan Faudu, Pulau Hiri, Kota Ternate',
                    'x' => '127.315216',
                    'y' => '0.913062',
                    'kelurahan' => 'Faudu',
                    'kecamatan' => 'Pulau Hiri',
                    'kota' => 'Kota Ternate',
                    'deskripsi' => 'Aliran lava tua di Pulau Hiri, menunjukkan ekspansi aktivitas vulkanik luar Pulau Ternate utama.',
                ],
                [
                    'nama' => 'Ignimbrite Gurabala Tomajiko',
                    'slug' => 'ignimbrite-gurabala-tomajiko',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kelurahan Tomajiko, Pulau Hiri, Kota Ternate',
                    'x' => '127.305531',
                    'y' => '0.902462',
                    'kelurahan' => 'Tomajiko',
                    'kecamatan' => 'Pulau Hiri',
                    'kota' => 'Kota Ternate',
                    'deskripsi' => 'Lapisan ignimbrite tebal dari runtuhan awan panas vulkanik, merekam aliran material panas yang luas.',
                ],
            ],
            'biologi' => [
                [
                    'nama' => 'Kuskus Matabiru (Phalanger matabiru)',
                    'slug' => 'kuskus-matabiru-phalanger-matabiru',
                    'image' => 'kuso.jpeg',
                    'lokasi' => 'Kel. Takome (Ekowisata Pulo Tareba, sisi barat Danau Tolire); juga tercatat di Kulaba & Kelurahan Sasa',
                    'kecamatan' => 'Ternate Barat; Ternate Selatan',
                    'x' => '127.3110884',
                    'y' => '0.8367390',
                    'deskripsi' => 'Satwa khas Ternate yang hidup di hutan dan area pesisir, menjadi salah satu ikon biodiversity Geopark.',
                ],
                [
                    'nama' => 'Burung Kasturi/Nuri Ternate (Lorius garrulus)',
                    'slug' => 'burung-kasturi-nuri-ternate-lorius-garrulus',
                    'image' => 'burung-nuri.png',
                    'lokasi' => 'Kel. Takome Kawasan Danau Tolire (hutan primer/sekunder ke arah barat) dan sekitar Ngade',
                    'kecamatan' => 'Ternate Barat; Ternate Selatan',
                    'x' => '127.3132751',
                    'y' => '0.8384141',
                    'deskripsi' => 'Burung endemik Ternate yang sering dijumpai di hutan sekitar Danau Tolire.',
                ],
                [
                    'nama' => 'Cengkeh (Syzygium aromaticum L)',
                    'slug' => 'cengkeh-syzygium-aromaticum',
                    'image' => 'bg2.jpeg',
                    'lokasi' => 'Kel. Marikurubu (Dusun/Lingkungan Tongole, kompleks Air Tege-tege) — lokasi cengkeh Afo, cengkeh tertua di dunia; juga tersebar luas di kebun-kebun lereng Gamalama',
                    'kecamatan' => 'Ternate Tengah (cengkeh Afo); tersebar juga di Ternate Pulau, Ternate Barat',
                    'x' => '127.3579946',
                    'y' => '0.7907052',
                    'deskripsi' => 'Tanaman rempah historis yang menjadi bagian penting dari identitas dan ekonomi lokal Ternate.',
                ],
                [
                    'nama' => 'Pala (Myristica fragrans)',
                    'slug' => 'pala-myristica-fragrans',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kel. Marikurubu dan Kel. Foramadiahi (kebun pala-cengkeh di lereng selatan Gamalama)',
                    'kecamatan' => 'Ternate Tengah; Ternate Pulau',
                    'x' => '127.3551421',
                    'y' => '0.8005454',
                    'deskripsi' => 'Rempah pala dan kebun pala yang menjadi simbol kekayaan agro-biotik Ternate.',
                ],
                [
                    'nama' => 'Bunga Telang (Clitoria ternatea)',
                    'slug' => 'bunga-telang-clitoria-ternatea',
                    'image' => 'soya-soya.jpeg',
                    'lokasi' => 'Tumbuh tersebar (liar/budidaya pekarangan) di berbagai kelurahan — tidak ada sentra lokasi spesifik tercatat',
                    'kecamatan' => 'Tersebar di seluruh kecamatan Kota Ternate',
                    'x' => '127.3523061',
                    'y' => '0.7650049',
                    'deskripsi' => 'Tumbuhan yang sering digunakan sebagai pewarna alami dan bagian dari kehidupan masyarakat lokal.',
                ],
                [
                    'nama' => 'Tanaman Patah Tulang (Euphorbia tirucalli)',
                    'slug' => 'tanaman-patah-tulang-euphorbia-tirucalli',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kel. Kulaba (Batu Angus) merupakan tanaman asli dan endemik Pulau Ternate. Tanaman ini mudah ditemukan tumbuh liar atau merambat di pekarangan rumah, pagar, pinggiran hutan, dan dekat tepi kali mati di seluruh wilayah Ternate',
                    'kecamatan' => 'Tersebar di seluruh kecamatan Kota Ternate',
                    'x' => '127.3654000',
                    'y' => '0.8466237',
                    'deskripsi' => 'Tanaman endemik yang merupakan bagian dari vegetasi khas Ternate dan adat setempat.',
                ],
            ],
            'budaya' => [
                [
                    'nama' => 'Benteng Kastela',
                    'slug' => 'benteng-kastela',
                    'image' => 'benteng.jpg',
                    'lokasi' => 'Kel. Kastela',
                    'kecamatan' => 'Pulau Ternate',
                    'x' => '127.3134',
                    'y' => '0.7600',
                    'jenis' => 'Benda',
                    'deskripsi' => 'Benteng Kastela merupakan salah satu benteng bersejarah peninggalan Kesultanan Ternate dan VOC.',
                ],
                [
                    'nama' => 'Benteng Fuerza Nueva',
                    'slug' => 'benteng-fuerza-nueva',
                    'image' => 'benteng.jpg',
                    'lokasi' => 'Kel. Kastela',
                    'kecamatan' => 'Pulau Ternate',
                    'x' => '127.3139',
                    'y' => '0.7646',
                    'jenis' => 'Benda',
                    'deskripsi' => 'Benteng Fuerza Nueva adalah saksi sejarah kekuasaan kolonial dan pertahanan pelabuhan Ternate.',
                ],
                [
                    'nama' => 'Benteng Kota Janji',
                    'slug' => 'benteng-kota-janji',
                    'image' => 'benteng.jpg',
                    'lokasi' => 'Kel. Kalumata / Ngade',
                    'kecamatan' => 'Ternate Selatan',
                    'x' => '127.3685',
                    'y' => '0.7816',
                    'jenis' => 'Benda',
                    'deskripsi' => 'Benteng Kota Janji merupakan salah satu benteng pertahanan yang menandai persaingan wilayah di Ternate.',
                ],
                [
                    'nama' => 'Benteng Kalamata',
                    'slug' => 'benteng-kalamata',
                    'image' => 'benteng.jpg',
                    'lokasi' => 'Kel. Kayu Merah',
                    'kecamatan' => 'Ternate Selatan',
                    'x' => '127.3732',
                    'y' => '0.7623',
                    'jenis' => 'Benda',
                    'deskripsi' => 'Benteng Kalamata menjadi salah satu lokasi peninggalan bersejarah yang merekam masa peninggalan Sultan Ternate.',
                ],
                [
                    'nama' => 'Benteng Talangame',
                    'slug' => 'benteng-talangame',
                    'image' => 'benteng.jpg',
                    'lokasi' => 'Sebutan lain/lokasi asal Benteng Kalamata',
                    'kecamatan' => 'Ternate Selatan',
                    'x' => '127.3732',
                    'y' => '0.7623',
                    'jenis' => 'Benda',
                    'deskripsi' => 'Benteng Talangame merupakan nama lain dari Benteng Kalamata, mencerminkan sejarah lokal dan penamaan wilayah.',
                ],
                [
                    'nama' => 'Benteng Callaboeka',
                    'slug' => 'benteng-callaboeka',
                    'image' => 'benteng.jpg',
                    'lokasi' => 'Kel. Sangaji (dekat Benteng Toloko)',
                    'kecamatan' => 'Ternate Utara',
                    'x' => '127.3882',
                    'y' => '0.8142',
                    'jenis' => 'Benda',
                    'deskripsi' => 'Benteng Callaboeka berdiri dekat garis pantai dan berperan dalam pertahanan pesisir Ternate.',
                ],
                [
                    'nama' => 'Benteng Voorbrught',
                    'slug' => 'benteng-voorbrught',
                    'image' => 'benteng.jpg',
                    'lokasi' => 'Area Benteng Oranje',
                    'kecamatan' => 'Ternate Tengah',
                    'x' => '127.3822',
                    'y' => '0.7925',
                    'jenis' => 'Benda',
                    'deskripsi' => 'Benteng Voorbrught berada di kawasan yang sama dengan Benteng Oranje dan menjadi bagian sejarah kolonial Ternate.',
                ],
                [
                    'nama' => 'Benteng Oranje',
                    'slug' => 'benteng-oranje',
                    'image' => 'benteng-orange.jpg',
                    'lokasi' => 'Kel. Gamalama',
                    'kecamatan' => 'Ternate Tengah',
                    'x' => '127.3822',
                    'y' => '0.7925',
                    'jenis' => 'Benda',
                    'deskripsi' => 'Benteng Oranje adalah ikon sejarah kolonial Belanda di Ternate yang masih menjadi objek wisata budaya.',
                ],
                [
                    'nama' => 'Kedaton Kesultanan',
                    'slug' => 'kedaton-kesultanan',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kel. Salero',
                    'kecamatan' => 'Ternate Utara',
                    'x' => '127.3841',
                    'y' => '0.8005',
                    'jenis' => 'Benda',
                    'deskripsi' => 'Kedaton Kesultanan Ternate adalah pusat pemerintahan tradisional dan budaya kerajaan.',
                ],
                [
                    'nama' => 'Benteng Kotanaka',
                    'slug' => 'benteng-kotanaka',
                    'image' => 'benteng.jpg',
                    'lokasi' => 'Benteng Sentosa (samping Kedaton Sultan)',
                    'kecamatan' => 'Ternate Utara',
                    'x' => '127.3838',
                    'y' => '0.8007',
                    'jenis' => 'Benda',
                    'deskripsi' => 'Benteng Kotanaka berdiri di samping area Kedaton dan menambah jaringan pertahanan kota Ternate.',
                ],
                [
                    'nama' => 'Benteng Toloko',
                    'slug' => 'benteng-toloko',
                    'image' => 'benteng.jpg',
                    'lokasi' => 'Kel. Sangaji Utara',
                    'kecamatan' => 'Ternate Utara',
                    'x' => '127.3881',
                    'y' => '0.8139',
                    'jenis' => 'Benda',
                    'deskripsi' => 'Benteng Toloko merupakan salah satu benteng pesisir yang menjaga akses masuk pelabuhan.',
                ],
                [
                    'nama' => 'Benteng Willemstad',
                    'slug' => 'benteng-willemstad',
                    'image' => 'benteng.jpg',
                    'lokasi' => 'Benteng Takome, Kel. Takome',
                    'kecamatan' => 'Barat Laut Ternate / Pulau Ternate',
                    'x' => '127.3129',
                    'y' => '0.8351',
                    'jenis' => 'Benda',
                    'deskripsi' => 'Benteng Willemstad menjadi bagian warisan geostrategis di sisi barat laut Ternate.',
                ],
                [
                    'nama' => 'Klenteng Thian Hou Kiong',
                    'slug' => 'klenteng-thian-hou-kiong',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kel. Gamalama',
                    'kecamatan' => 'Ternate Tengah',
                    'x' => '127.3871',
                    'y' => '0.7887',
                    'jenis' => 'Benda',
                    'deskripsi' => 'Klenteng Thian Hou Kiong menunjukkan keragaman spiritual dan arsitektur di Ternate.',
                ],
                [
                    'nama' => 'Gereja St. Willibrordus',
                    'slug' => 'gereja-st-willibrordus',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kel. Tanah Raja',
                    'kecamatan' => 'Ternate Tengah',
                    'x' => '127.3883',
                    'y' => '0.7891',
                    'jenis' => 'Benda',
                    'deskripsi' => 'Gereja St. Willibrordus merupakan warisan misionaris yang menjadi bagian sejarah agama di Ternate.',
                ],
                [
                    'nama' => 'Mesjid Sultan',
                    'slug' => 'mesjid-sultan',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Sigi Lamo, Kel. Soa Sio',
                    'kecamatan' => 'Ternate Utara',
                    'x' => '127.3844',
                    'y' => '0.7994',
                    'jenis' => 'Benda',
                    'deskripsi' => 'Mesjid Sultan menjadi pusat keagamaan dan tradisi Islam di komunitas Ternate.',
                ],
                [
                    'nama' => 'Kuburan Keramat/ Jere Kulaba',
                    'slug' => 'kuburan-keramat-jere-kulaba',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kel. Kulaba',
                    'kecamatan' => 'Ternate Barat',
                    'x' => '127.3583',
                    'y' => '0.8428',
                    'jenis' => 'Benda',
                    'deskripsi' => 'Kuburan keramat Jere Kulaba adalah situs ziarah yang penting dalam tradisi lokal Ternate.',
                ],
                [
                    'nama' => 'Ritual Uci Dowong',
                    'slug' => 'ritual-uci-dowong',
                    'image' => 'tari-lenso.jpeg',
                    'lokasi' => 'Kel. Sulamadaha',
                    'kecamatan' => 'Ternate Barat',
                    'x' => '127.3365',
                    'y' => '0.8627',
                    'jenis' => 'Tak Benda - Ritual/ Tradisi',
                    'deskripsi' => 'Ritual Uci Dowong adalah tradisi lokal yang melibatkan doa dan upacara adat masyarakat Ternate.',
                ],
                [
                    'nama' => 'Ritual Kololi Kie Mote Ngolo',
                    'slug' => 'ritual-kololi-kie-mote-ngolo',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kel. Salero',
                    'kecamatan' => 'Ternate Utara',
                    'x' => '127.3883',
                    'y' => '0.8013',
                    'jenis' => 'Tak Benda - Ritual/ Tradisi',
                    'deskripsi' => 'Ritual Kololi Kie Mote Ngolo merupakan bagian tradisi spiritual Kesultanan Ternate.',
                ],
                [
                    'nama' => 'Tradisi Ela-Ela',
                    'slug' => 'tradisi-ela-ela',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kedaton Kesultanan Ternate Kel. Salero',
                    'kecamatan' => 'Ternate Utara',
                    'x' => '127.3841',
                    'y' => '0.8007',
                    'jenis' => 'Tak Benda - Ritual/ Tradisi',
                    'deskripsi' => 'Tradisi Ela-Ela adalah tradisi syukuran laut yang masih dilaksanakan oleh masyarakat setempat.',
                ],
                [
                    'nama' => 'Tradisi Ziarah Jere',
                    'slug' => 'tradisi-ziarah-jere',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kel. Kulaba',
                    'kecamatan' => 'Ternate Barat',
                    'x' => '127.3583',
                    'y' => '0.8428',
                    'jenis' => 'Tak Benda - Ritual/ Tradisi',
                    'deskripsi' => 'Tradisi Ziarah Jere merupakan kegiatan ziarah ke situs-situs keramat dan leluhur.',
                ],
                [
                    'nama' => 'Upacara Joko Kaha',
                    'slug' => 'upacara-joko-kaha',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kedaton Kesultanan Ternate Kel. Salero',
                    'kecamatan' => 'Ternate Utara',
                    'x' => '127.3841',
                    'y' => '0.8007',
                    'jenis' => 'Tak Benda - Ritual/ Tradisi',
                    'deskripsi' => 'Upacara Joko Kaha adalah ritual penting dalam kalender budaya Kesultanan Ternate.',
                ],
                [
                    'nama' => 'Tari Soya-Soya',
                    'slug' => 'tari-soya-soya',
                    'image' => 'soya-soya.jpeg',
                    'lokasi' => 'Panggung Sunyie Lamo Lapangan Ngara Lamo Kel. Soa-Sio',
                    'kecamatan' => 'Ternate Utara',
                    'x' => '127.3854',
                    'y' => '0.8007',
                    'jenis' => 'Tak Benda - Tarian',
                    'deskripsi' => 'Tari Soya-Soya menggambarkan semangat perjuangan dan kegembiraan masyarakat Ternate.',
                ],
                [
                    'nama' => 'Tari Tide-Tide',
                    'slug' => 'tari-tide-tide',
                    'image' => 'benteng-orange.jpg',
                    'lokasi' => 'Panggung Pertunjukan Batu Angus Kel. Kulaba',
                    'kecamatan' => 'Ternate Barat',
                    'x' => '127.3653',
                    'y' => '0.8464',
                    'jenis' => 'Tak Benda - Tarian',
                    'deskripsi' => 'Tari Tide-Tide merupakan tarian tradisi yang sering dipentaskan saat acara kebudayaan setempat.',
                ],
                [
                    'nama' => 'Tari Salai Jin',
                    'slug' => 'tari-salai-jin',
                    'image' => 'peta-geopark.jpg',
                    'lokasi' => 'Kedaton Kesultanan Ternate Kel. Salero',
                    'kecamatan' => 'Ternate Utara',
                    'x' => '127.3841',
                    'y' => '0.8007',
                    'jenis' => 'Tak Benda - Tarian',
                    'deskripsi' => 'Tari Salai Jin adalah tarian upacara yang memadukan unsur musik dan gerakan tradisional Ternate.',
                ],
                [
                    'nama' => 'Tari Lalayon',
                    'slug' => 'tari-lalayon',
                    'image' => 'tari-lenso.jpeg',
                    'lokasi' => 'Pendopo Benteng Fort Oranje Kel. Gamalama',
                    'kecamatan' => 'Ternate Tengah',
                    'x' => '127.3867',
                    'y' => '0.7928',
                    'jenis' => 'Tak Benda - Tarian',
                    'deskripsi' => 'Tari Lalayon merupakan tarian pembukaan untuk menyambut tamu dan perayaan adat.',
                ],
            ],
        ];
    }

    public static function item(string $section, string $slug): ?array
    {
        $items = self::items();

        if (!isset($items[$section])) {
            return null;
        }

        foreach ($items[$section] as $item) {
            if (Str::slug($item['nama']) === $slug) {
                return $item;
            }
        }

        return null;
    }
}
